Resources:
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This is the public security group 
      VpcId: !Ref VPC
      Tags: 
        - Key: Name
          Value: Public security group

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This is the private security group 
      VpcId: !Ref VPC
      Tags: 
        - Key: Name
          Value: Private security group