Resources:
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This is the public security group 
      VpcId: !Ref VPC
      Tags: 
        - Key: Name
          Value: Public security group

  PublicSecurityGroupIngress:
     Type: AWS::EC2::SecurityGroupIngress
     Properties:
      CidrIp: 0.0.0.0/0
      Description: Allow for HTTPS inound
      FromPort: 443
      GroupId: !Ref PublicSecurityGroup
      IpProtocol: tcp
      ToPort: 443

  PublicSecurityGroupEgress:
   Type: AWS::EC2::SecurityGroupEgress
   Properties:
      CidrIp: 0.0.0.0/0
      Description: Allow for HTTPS outbound
      FromPort: 443
      GroupId: !Ref PublicSecurityGroup
      IpProtocol: tcp
      ToPort: 443

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This is the private security group 
      VpcId: !Ref VPC
      Tags: 
        - Key: Name
          Value: Private security group