Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/15
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: FridayHITT_PROD_VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.0.0/16
      AvailabilityZone: eu-west-1a
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: FridayHITT_Public_Subnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.0.0/20
      AvailabilityZone: eu-west-1a
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: FridayHITT_Private_Subnet

  InternetGateway:
   Type: AWS::EC2::InternetGateway
   Properties:
    Tags: 
    - Key: Name
      Value: FridayHITT_InternetGateway